spring.application.name=inventory-consumer

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${SERVER_PORT:8082}

# RabbitMQ conexión
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# RabbitMQ - módulo location
rabbitmq.exchange.location=location.exchange
rabbitmq.queue.location.create=location.create
rabbitmq.queue.location.update=location.update
rabbitmq.queue.location.patch=location.patch


rabbitmq.routing-key.location.create=location.create
rabbitmq.routing-key.location.update=location.update
rabbitmq.routing-key.location.patch=location.patch

rabbitmq.exchange.product=product.exchange

rabbitmq.queue.product.create=product.create.queue
rabbitmq.queue.product.update=product.update.queue
rabbitmq.queue.product.patch=product.patch.queue
rabbitmq.queue.product.delete=product.delete.queue

rabbitmq.routing-key.product.create=product.create
rabbitmq.routing-key.product.update=product.update
rabbitmq.routing-key.product.patch=product.patch
rabbitmq.routing-key.product.delete=product.delete

rabbitmq.exchange.sales.create.request=sales.create.request.exchange
rabbitmq.exchange.sales.response=sales.response.exchange

rabbitmq.queue.sales.create.request=sales.create.request.queue
rabbitmq.queue.sales.response=sales.response.queue

rabbitmq.routing-key.sales.create.request=sales.create.request
rabbitmq.routing-key.sales.response=sales.response

# RabbitMQ - módulo transfer
rabbitmq.exchange.transfer.request=create.transfer.request.exchange
rabbitmq.exchange.transfer.response=create.transfer.response.exchange
rabbitmq.exchange.transfer.status.request=update.transfer.status.request.exchange

rabbitmq.queue.transfer.request=create.transfer.request.queue
rabbitmq.queue.transfer.response=create.transfer.response.queue
rabbitmq.queue.transfer.status.request=update.transfer.status.request.queue

rabbitmq.routing-key.transfer.request=create.transfer.request
rabbitmq.routing-key.transfer.response=create.transfer.response
rabbitmq.routing-key.transfer.status.request=update.transfer.status.request
